
(in-package :ulubis.wmii.tests)

(defvar *reposition-called*)
(defvar *activate-called*)
(defvar *last-active*)

(defun test-reposition-callback (surface top bottom left right
                                 &key (render-surface t) (visible t) fullscreen tabs)
  (declare (ignore top bottom left right render-surface visible fullscreen tabs))
  (push surface *reposition-called*))

(defun test-activate-callback (surface)
  (setf *last-active* surface)
  (push surface *activate-called*))

(defmacro test-layout ((layout-var name) &body body)
  `(subtest ,name
     (let ((,layout-var (make-instance 'layout
                                       :reposition-callback #'test-reposition-callback
                                       :activate-callback #'test-activate-callback))
           (*reposition-called* nil)
           (*activate-called* nil)
           (*last-active* nil))
       ,@body)))

(plan 9)

(test-layout (l "add")
  (add-surface 't1 l)
  (is *reposition-called* '(t1))
  (is *activate-called* '(t1))
  (is *last-active* 't1))

(test-layout (l "remove 1")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (add-surface 't3 l)
  (is *last-active* 't3)
  (remove-surface 't2 l)
  (is *last-active* 't3)
  (remove-surface 't3 l)
  (is *last-active* 't1)
  (add-surface 't4 l)
  (move-cursor-up l)
  (is *last-active* 't1)
  (remove-surface 't1 l)
  (is *last-active* 't4))

(test-layout (l "remove 2")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (add-surface 't3 l)
  (is *last-active* 't3)
  (move-cursor-up l)
  (is *last-active* 't2)
  (remove-surface 't2 l)
  (is *last-active* 't1))

(test-layout (l "remove column 1")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (move-window-right l)
  (move-window-left l)
  (is (length (ulubis.wmii::columns l)) 1)
  (is *last-active* 't2))

(test-layout (l "remove column 2")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (move-window-right l)
  (remove-surface 't2 l)
  (is (length (ulubis.wmii::columns l)) 1)
  (is *last-active* 't1))

(test-layout (l "remove column 3")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (move-window-right l)
  (move-cursor-left l)
  (remove-surface 't1 l)
  (is (length (ulubis.wmii::columns l)) 1)
  (is *last-active* 't2))

(test-layout (l "move cursor")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (is *last-active* 't2)
  (add-surface 't3 l)
  (is *last-active* 't3)
  (move-cursor-up l)
  (is *last-active* 't2))

(test-layout (l "move window left/right")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (is *last-active* 't2)
  (move-window-right l)
  (is *last-active* 't2)
  (is (length (ulubis.wmii::columns l)) 2)
  (add-surface 't3 l)
  (move-cursor-left l)
  (is *last-active* 't1))

(test-layout (l "move window up/down")
  (add-surface 't1 l)
  (add-surface 't2 l)
  (add-surface 't3 l)
  (move-window-down l)
  (move-cursor-up l)
  (is *last-active* 't2)
  (move-cursor-down l)
  (move-window-up l)
  (move-window-up l)
  (move-cursor-down l)
  (is *last-active* 't1)
  (move-cursor-up l)
  (move-window-up l)
  (move-cursor-down l)
  (is *last-active* 't1))

(finalize)
